# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbbab1f71527b6e51bca73fde63a49dfccf20fd82d45f83cbda77074f9a21d99968ffb149ae2c6a78e9ba8609a89b29ac1cb52f07e578ddc72f10752e89fcd9

test:
  secret_key_base: dfa3db7bd813ea98774b86644726547ac45a7bf8d4fe1f49f1f7b054f6d95c796fdb91eb3c2da59d04063814bb137c6f82c0fce105ead89abf602494654a940c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
